export const productCards = [
  {
    id: 1,
    urlSm: './images/bouquet-cards/bouquet-image-1-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-1-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-1-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-1-lg.webp',
    title: 'Ягідний букет',
    price: 360,
  },
  {
    id: 2,
    urlSm: './images/bouquet-cards/bouquet-image-2-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-2-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-2-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-2-lg.webp',
    title: 'Букет "Ковбаска-сир"',
    price: 810,
  },
  {
    id: 3,
    urlSm: './images/bouquet-cards/bouquet-image-3-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-3-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-3-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-3-lg.webp',
    title: 'Букет з абрикосів',
    price: 375,
  },
  {
    id: 4,
    urlSm: './images/bouquet-cards/bouquet-image-4-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-4-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-4-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-4-lg.webp',
    title: 'Букет «Milka»',
    price: 410,
  },
  {
    id: 5,
    urlSm: './images/bouquet-cards/bouquet-image-5-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-5-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-5-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-5-lg.webp',
    title: 'Букет «Кіндер-сюрприз»',
    price: 540,
  },
  {
    id: 6,
    urlSm: './images/bouquet-cards/bouquet-image-6-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-6-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-6-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-6-lg.webp',
    title: 'Букет «Cерце з сухофруктів»',
    price: 575,
  },
  {
    id: 7,
    urlSm: './images/bouquet-cards/bouquet-image-7-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-7-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-7-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-7-lg.webp',
    title: 'Букет з горіхів',
    price: 630,
  },
  {
    id: 8,
    urlSm: './images/bouquet-cards/bouquet-image-8-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-8-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-8-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-8-lg.webp',
    title: 'Букет з зефіру та шоколаду',
    price: 280,
  },
  {
    id: 9,
    urlSm: './images/bouquet-cards/bouquet-image-9-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-9-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-9-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-9-lg.webp',
    title: 'Букет «Єдиноріжка» з маршмеллоу',
    price: 340,
  },
  {
    id: 10,
    urlSm: './images/bouquet-cards/bouquet-image-10-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-10-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-10-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-10-lg.webp',
    title: 'Букет з сухофруктами',
    price: 520,
  },
  {
    id: 11,
    urlSm: './images/bouquet-cards/bouquet-image-11-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-11-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-11-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-11-lg.webp',
    title: 'Букет «Ковбаска-сир-багет»',
    price: 760,
  },
  {
    id: 12,
    urlSm: './images/bouquet-cards/bouquet-image-12-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-12-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-12-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-12-lg.webp',
    title: 'Букет з горіхами та сухофруктами',
    price: 610,
  },
  {
    id: 13,
    urlSm: './images/bouquet-cards/bouquet-image-13-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-13-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-13-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-13-lg.webp',
    title: 'Букет з шоколаду та зефіру',
    price: 360,
  },
  {
    id: 14,
    urlSm: './images/bouquet-cards/bouquet-image-14-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-14-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-14-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-14-lg.webp',
    title: 'Букет «Мармеладки»',
    price: 335,
  },
  {
    id: 15,
    urlSm: './images/bouquet-cards/bouquet-image-15-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-15-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-15-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-15-lg.webp',
    title: 'Букет ягідний з квітами',
    price: 405,
  },
  {
    id: 16,
    urlSm: './images/bouquet-cards/bouquet-image-16-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-16-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-16-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-16-lg.webp',
    title: 'Букет «Cухофруктовий вінок»',
    price: 550,
  },
  {
    id: 17,
    urlSm: './images/bouquet-cards/bouquet-image-17-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-17-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-17-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-17-lg.webp',
    title: "Букет «М'ясний кошик»",
    price: 1160,
  },
  {
    id: 18,
    urlSm: './images/bouquet-cards/bouquet-image-18-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-18-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-18-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-18-lg.webp',
    title: 'Букет з сухофруктів з зеленню',
    price: 490,
  },
  {
    id: 19,
    urlSm: './images/bouquet-cards/bouquet-image-19-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-19-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-19-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-19-lg.webp',
    title: 'Букет з печіва',
    price: 320,
  },
  {
    id: 20,
    urlSm: './images/bouquet-cards/bouquet-image-20-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-20-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-20-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-20-lg.webp',
    title: 'Букет «Millenium&Ferrero» з фіставшками',
    price: 820,
  },
  {
    id: 21,
    urlSm: './images/bouquet-cards/bouquet-image-21-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-21-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-21-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-21-lg.webp',
    title: 'Букет «Розовий маршмеллоу»',
    price: 495,
  },
  {
    id: 22,
    urlSm: './images/bouquet-cards/bouquet-image-22-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-22-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-22-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-22-lg.webp',
    title: 'Букет «Cерце з сухофруктами»',
    price: 610,
  },
  {
    id: 23,
    urlSm: './images/bouquet-cards/bouquet-image-23-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-23-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-23-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-23-lg.webp',
    title: 'Букет ягідний з полуницею',
    price: 480,
  },
  {
    id: 24,
    urlSm: './images/bouquet-cards/bouquet-image-24-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-24-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-24-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-24-lg.webp',
    title: 'Букет з сухофруктів з ананасною розою',
    price: 740,
  },
  {
    id: 25,
    urlSm: './images/bouquet-cards/bouquet-image-25-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-25-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-25-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-25-lg.webp',
    title: 'Букет «Міккі-маус» з маршмеллоу',
    price: 480,
  },
  {
    id: 26,
    urlSm: './images/bouquet-cards/bouquet-image-26-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-26-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-26-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-26-lg.webp',
    title: 'Букет «Хогвардс» з цукатами та зефіром',
    price: 570,
  },
  {
    id: 27,
    urlSm: './images/bouquet-cards/bouquet-image-27-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-27-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-27-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-27-lg.webp',
    title: 'Букет з цукатами та сухофруктами',
    price: 600,
  },
  {
    id: 28,
    urlSm: './images/bouquet-cards/bouquet-image-28-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-28-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-28-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-28-lg.webp',
    title: 'Букет з цукатами, сухофруктами та горіхами',
    price: 640,
  },
  {
    id: 29,
    urlSm: './images/bouquet-cards/bouquet-image-29-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-29-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-29-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-29-lg.webp',
    title: 'Букет з цукерок в коробці',
    price: 390,
  },
  {
    id: 30,
    urlSm: './images/bouquet-cards/bouquet-image-30-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-30-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-30-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-30-lg.webp',
    title: 'Букет з цукатами великий',
    price: 720,
  },
  {
    id: 31,
    urlSm: './images/bouquet-cards/bouquet-image-31-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-31-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-31-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-31-lg.webp',
    title: 'Букет «Lion-Snickers»',
    price: 520,
  },
  {
    id: 32,
    urlSm: './images/bouquet-cards/bouquet-image-32-sm.jpg',
    urlSmWebp: './images/bouquet-cards/bouquet-image-32-sm.webp',
    urlLg: './images/bouquet-cards/bouquet-image-32-lg.jpg',
    urlLgWebp: './images/bouquet-cards/bouquet-image-32-lg.webp',
    title: 'Букет з цукатами в горщику',
    price: 390,
  },
]